/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package temporizador_bigbang;

import temporizador_bigbang.Cronometro;

/**
 *
 * @author juandiegohernandezamaya
 */
public class Ventana extends javax.swing.JFrame {

    Cronometro c = new Cronometro();
    
    public Ventana() {
        initComponents();
        setVisible(true); //Hacer visible la interfaz grafica
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PTiempos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        STSegundo = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        BReset = new javax.swing.JButton();
        SRonda = new javax.swing.JSpinner();
        STMinuto = new javax.swing.JSpinner();
        jLabel11 = new javax.swing.JLabel();
        SDHora = new javax.swing.JSpinner();
        jLabel12 = new javax.swing.JLabel();
        SDMinuto = new javax.swing.JSpinner();
        jLabel13 = new javax.swing.JLabel();
        SDSegundo = new javax.swing.JSpinner();
        jSeparator1 = new javax.swing.JSeparator();
        STHora = new javax.swing.JSpinner();
        BIniciar = new javax.swing.JButton();
        PTemporizador = new javax.swing.JPanel();
        LTexto = new javax.swing.JLabel();
        LRonda = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        LMinuto = new javax.swing.JLabel();
        LHora = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        LSegundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TEMPORIZADOR");
        setMinimumSize(new java.awt.Dimension(500, 500));
        setResizable(false);
        setSize(new java.awt.Dimension(500, 500));
        getContentPane().setLayout(null);

        PTiempos.setLayout(null);

        jLabel1.setText("Tiempo de Descanso");
        PTiempos.add(jLabel1);
        jLabel1.setBounds(40, 170, 140, 16);

        jLabel2.setText("# Rondas");
        PTiempos.add(jLabel2);
        jLabel2.setBounds(40, 40, 80, 16);

        STSegundo.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 1));
        PTiempos.add(STSegundo);
        STSegundo.setBounds(350, 120, 50, 26);

        jLabel4.setText("Tiempo de Trabajo");
        PTiempos.add(jLabel4);
        jLabel4.setBounds(40, 90, 120, 16);

        jLabel5.setText("H:");
        PTiempos.add(jLabel5);
        jLabel5.setBounds(100, 120, 20, 20);

        jLabel7.setText("M:");
        PTiempos.add(jLabel7);
        jLabel7.setBounds(210, 120, 20, 20);

        jLabel8.setText("S:");
        PTiempos.add(jLabel8);
        jLabel8.setBounds(330, 120, 20, 20);

        BReset.setText("RESET");
        BReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BResetActionPerformed(evt);
            }
        });
        PTiempos.add(BReset);
        BReset.setBounds(390, 60, 90, 29);

        SRonda.setModel(new javax.swing.SpinnerNumberModel(0, 0, 99, 1));
        PTiempos.add(SRonda);
        SRonda.setBounds(170, 40, 50, 26);

        STMinuto.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 1));
        PTiempos.add(STMinuto);
        STMinuto.setBounds(230, 120, 50, 26);

        jLabel11.setText("H:");
        PTiempos.add(jLabel11);
        jLabel11.setBounds(100, 200, 20, 20);

        SDHora.setModel(new javax.swing.SpinnerNumberModel(0, 0, 23, 1));
        PTiempos.add(SDHora);
        SDHora.setBounds(120, 200, 50, 26);

        jLabel12.setText("M:");
        PTiempos.add(jLabel12);
        jLabel12.setBounds(210, 200, 20, 20);

        SDMinuto.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 1));
        PTiempos.add(SDMinuto);
        SDMinuto.setBounds(230, 200, 50, 26);

        jLabel13.setText("S:");
        PTiempos.add(jLabel13);
        jLabel13.setBounds(330, 200, 20, 20);

        SDSegundo.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 1));
        PTiempos.add(SDSegundo);
        SDSegundo.setBounds(350, 200, 50, 26);
        PTiempos.add(jSeparator1);
        jSeparator1.setBounds(0, 240, 500, 10);

        STHora.setModel(new javax.swing.SpinnerNumberModel(0, 0, 23, 1));
        PTiempos.add(STHora);
        STHora.setBounds(120, 120, 50, 26);

        BIniciar.setText("INICIAR");
        BIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BIniciarActionPerformed(evt);
            }
        });
        PTiempos.add(BIniciar);
        BIniciar.setBounds(390, 30, 92, 29);

        getContentPane().add(PTiempos);
        PTiempos.setBounds(0, 0, 500, 250);

        PTemporizador.setLayout(null);

        LTexto.setFont(new java.awt.Font("Comic Sans MS", 1, 22)); // NOI18N
        LTexto.setText("DESCANSA");
        PTemporizador.add(LTexto);
        LTexto.setBounds(190, 30, 130, 30);

        LRonda.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        LRonda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LRonda.setText("0");
        PTemporizador.add(LRonda);
        LRonda.setBounds(380, 110, 60, 90);

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        jLabel9.setText(":");
        PTemporizador.add(jLabel9);
        jLabel9.setBounds(180, 110, 20, 90);

        LMinuto.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        LMinuto.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LMinuto.setText("00");
        PTemporizador.add(LMinuto);
        LMinuto.setBounds(110, 110, 60, 90);

        LHora.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        LHora.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LHora.setText("00");
        PTemporizador.add(LHora);
        LHora.setBounds(20, 110, 60, 90);

        jLabel15.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        jLabel15.setText(":");
        PTemporizador.add(jLabel15);
        jLabel15.setBounds(90, 110, 20, 90);

        jLabel16.setText("Ronda:");
        PTemporizador.add(jLabel16);
        jLabel16.setBounds(390, 90, 43, 16);

        jLabel17.setText("Tiempo:");
        PTemporizador.add(jLabel17);
        jLabel17.setBounds(30, 90, 51, 16);

        LSegundo.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        LSegundo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LSegundo.setText("00");
        PTemporizador.add(LSegundo);
        LSegundo.setBounds(200, 110, 60, 90);

        getContentPane().add(PTemporizador);
        PTemporizador.setBounds(0, 250, 500, 250);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BResetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BResetActionPerformed

    private void BIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BIniciarActionPerformed
        
        //Enviar los valores ingresados por el usuario a las variables de la clase cronometro
        
        c.setRonda((int) SRonda.getValue());
        c.setThora((int) STHora.getValue());
        c.setTminuto((int) STMinuto.getValue());
        c.setTsegundo((int) STSegundo.getValue());
        c.setDhora((int) SDHora.getValue());
        c.setDminuto((int) SDMinuto.getValue());
        c.setDsegundo((int) SDSegundo.getValue());
        
        c.imprimir();
        
        //Establece los valores del temporizador
        
        LRonda.setText(c.getRonda());
        LHora.setText(c.getThora());
        LMinuto.setText(c.getTminuto());
        LSegundo.setText(c.getTsegundo());
        
        //Texto
        
        //LTexto.setText("DESCANSA");
        LTexto.setText("TRABAJA");
    }//GEN-LAST:event_BIniciarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BIniciar;
    private javax.swing.JButton BReset;
    private javax.swing.JLabel LHora;
    private javax.swing.JLabel LMinuto;
    private javax.swing.JLabel LRonda;
    private javax.swing.JLabel LSegundo;
    private javax.swing.JLabel LTexto;
    private javax.swing.JPanel PTemporizador;
    private javax.swing.JPanel PTiempos;
    private javax.swing.JSpinner SDHora;
    private javax.swing.JSpinner SDMinuto;
    private javax.swing.JSpinner SDSegundo;
    private javax.swing.JSpinner SRonda;
    private javax.swing.JSpinner STHora;
    private javax.swing.JSpinner STMinuto;
    private javax.swing.JSpinner STSegundo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
